# Generated by Django 2.1.1 on 2018-09-26 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a piece title', max_length=200)),
                ('composer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Composer')),
            ],
            options={
                'ordering': ['composer', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an organization name', max_length=200)),
                ('type', models.CharField(help_text='Enter an organization type', max_length=40)),
                ('size', models.CharField(help_text='Enter an organization size', max_length=40)),
                ('url', models.CharField(help_text='Enter an organization url', max_length=200)),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an concert name', max_length=200)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(help_text='Enter an concert venue', max_length=200)),
                ('city', models.CharField(help_text='Enter the concert city, state', max_length=200, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date', 'city', 'venue'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(help_text='Enter a surname', max_length=200)),
                ('firstname', models.CharField(help_text='Enter the rest of the name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an recording name', max_length=200)),
                ('venue', models.CharField(help_text='Enter an recording venue', max_length=200)),
                ('url', models.CharField(help_text='Enter an recording link', max_length=200)),
                ('date', models.DateField()),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Organization')),
                ('pieces', models.ManyToManyField(help_text='What pieces were in this concert?', to='app.Composition')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voicepart', models.CharField(help_text='Enter a voice part', max_length=40)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Person')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='performances',
            field=models.ManyToManyField(help_text='When/where was this performance?', to='app.PerformanceInstance'),
        ),
        migrations.AddField(
            model_name='performance',
            name='pieces',
            field=models.ManyToManyField(help_text='What pieces were in this concert?', to='app.Composition'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Person'),
        ),
        migrations.AddField(
            model_name='composer',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Person'),
        ),
    ]
